name: Automatic Release

on:
  push:
    branches:
      - main

permissions:
  actions: write
  attestations: write
  checks: write
  contents: write
  discussions: write
  id-token: write

jobs:
  candidate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      # Languages
      - uses: denoland/setup-deno@v2
        with:
          deno-version: v2.x
      # Publish
      # - uses: softprops/action-gh-release@v2
      #   with:
      #     discussion_category_name: Announcements
      #     generate_release_notes: true
      #     files: |
      #       LICENSE
      #       README.md
      - name: 'Set Deployment Version'
        uses: richardrigutins/replace-in-files@v2
        with:
          files: 'deno.jsonc'
          search-text: '{{VERSION}}'
          replacement-text: '0.1.0-rc.${{ github.sha }}'
      - name: 'Publish Package'
        run: deno publish --allow-dirty --set-version 0.1.0-rc.${{ github.sha }}
